### ISSUE TITLE
Missing instructions for running Docker

### ISSUE THREAD

**Issue by ngarnier** [colbertdb/colbertdb#6]
Following the Readme's instructions and trying to run `docker build . -t colbertdb:latest` will generate the following error:

```
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by rysloan4** [comment]
you'll need docker running. desktop if local. https://www.docker.com/products/docker-desktop/

**Comment by ngarnier** [comment]
yep, creating the issue to add relevant instructions in the Readme 👍

**Comment by rysloan4** [comment]
added
